### ISSUE TITLE
some dumb bug

### ISSUE THREAD

**Issue by jimmythinh** [lewisakura/RFU#15]
![Screenshot 2022-05-11 190250](https://user-images.githubusercontent.com/105362197/167845683-5d47c4e5-781e-4b0c-bfa4-532b38d90740.png)
its said that its running
![Screenshot 2022-05-11 190505](https://user-images.githubusercontent.com/105362197/167845710-e77df81d-e68d-4135-9cc2-7fd38d5f169c.png)
but its not working

**Comment by LewisTehMinerz** [comment]
Did you make sure to set the FPS cap higher than 60?

**Comment by jimmythinh** [comment]
yep,i did

**Comment by chad-the-lad** [comment]
I have the same problem, am i able to get some help.

**Comment by lewisakura** [comment]
CNR and no followup.
