### ISSUE TITLE
Update Check 

### ISSUE THREAD

**Issue by Blanker101** [lewisakura/RFU#23]
Every time I turn on my computer I always get the Update Check message saying I should update to 5.4.4 or whatever. I've already updated 3 times and it still thinks that I'm in a later version and need to update.

**Comment by lewisakura** [comment]
What version is reported here?
![image](https://user-images.githubusercontent.com/8019327/202140395-f35fcd85-db6d-46a9-8683-e789127107aa.png)

**Comment by Blanker101** [comment]
![image](https://user-images.githubusercontent.com/46302292/202617671-3f328c90-12ac-48c2-94a2-4f636d3a6a7d.png)
5.4.4, still getting the bug

**Comment by lewisakura** [comment]
I can't reproduce the bug. It shouldn't be happening at all considering that version there is what it looks for on GitHub, so I have no idea what's going on here.

**Comment by lewisakura** [comment]
Closing as a non-issue due to no followup and I can't reproduce it.
