### ISSUE TITLE
[ERROR] Variable scan failed! This is probably due to a Roblox update -- watch the github for any patches or a fix. :/

### ISSUE THREAD

**Issue by keeitinho65** [lewisakura/RFU#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please join the
[testing game](https://www.roblox.com/games/5885482504/FPS-Unlocker-Check) and take a screenshot as well to gather FPS information.

**Desktop (please complete the following information):**
 - Version [e.g. 5.3.1]

**Additional context**

**Comment by keeitinho65** [comment]
o bug teve ocorre por desatualização

**Comment by lewisakura** [comment]
If you're running 5.3.1, you are severely out of date. Please download the [latest release](https://github.com/lewisakura/RFU/releases/latest).
