### ISSUE TITLE
I PUT THE FPS UNLOCKER ON AND IT STILL IS NOT WORKING PLEASE FIX THIS THANK YOU

### ISSUE THREAD

**Issue by rsmmansoor** [lewisakura/RFU#25]
**Describe the bug**
A clear and concise description of what the bug     THE BUG IS THAT IM OPENING FPS UNLOCKER AND ITS NOT WORKING  PLS FOX THIS THANK YOU

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please join the
[testing game](https://www.roblox.com/games/5885482504/FPS-Unlocker-Check) and take a screenshot as well to gather FPS information.

**Desktop (please complete the following information):**
 - Version [e.g. 5.3.1]

**Additional context**

**Comment by lewisakura** [comment]
"Not working" is vague. What's not working?
