### ISSUE TITLE
fps unlocker has a error occur everytime i open it, i tried uninstalling still doesnt work "variable scan failed" im not sure if its a problem on my end or whats going on 

### ISSUE THREAD

**Issue by chironse** [lewisakura/RFU#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please join the
[testing game](https://www.roblox.com/games/5885482504/FPS-Unlocker-Check) and take a screenshot as well to gather FPS information.

**Desktop (please complete the following information):**
 - Version [e.g. 5.3.1]

**Additional context**

**Comment by lewisakura** [comment]
Please fill out the info template and reopen the issue. I can't help you if you don't.
