### ISSUE TITLE
With the lates roblox update the program doesn't work properly and is unable to find task scheduler

### ISSUE THREAD

**Issue by TheHol** [lewisakura/RFU#27]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please join the
[testing game](https://www.roblox.com/games/5885482504/FPS-Unlocker-Check) and take a screenshot as well to gather FPS information.

**Desktop (please complete the following information):**
 - Version [e.g. 5.3.1]

**Additional context**

**Comment by Yaboiidariel** [comment]
> go in any game and try to load the fps unlocker then this error msg will show up

![image](https://user-images.githubusercontent.com/131422494/233529920-77a69161-8196-459a-be3b-03ba8a0da0bb.png)

**Comment by YourAverageModder** [comment]
Im having the same issue. I don't know any fixes to this, so we might have to wait till they update it

**Comment by Kasanova22** [comment]
im getting this same issue

**Comment by ForBai** [comment]
same issue

**Comment by sixfloat** [comment]
Every time I launch Roblox, I'm reminded of how much I used to love playing the game with the FPS Unlocker. The feeling of seamless and smooth gameplay was something that I looked forward to every day. But now, that feeling is gone. The game feels choppy and laggy, and I find myself struggling to enjoy it like I used to. The lack of fluidity in the game makes me feel disconnected from it. I miss the way the game used to make me feel; the joy and excitement that it brought me have faded away. It's as though a part of me is missing, and I can't seem to get it back. The realization that I can no longer play the game with the same level of enjoyment and ease has left me feeling sad and frustrated. It's like losing something that you cherish and not being able to find it again. The FPS Unlocker was a tool that brought me closer to the game, and now that it's gone, I feel empty and distant from it.

**Comment by lewisakura** [comment]
Unfortunately I cannot replicate this issue, therefore I cannot issue a fix at present. The best I can recommend is to reopen RFU when running Roblox which might give you better luck. There isn't a lot of information here that I can work with.

**Comment by lewisakura** [comment]
I have been informed this is related to the new Byfron anticheat solution that Roblox has been rolling out to a % of its users. There is nothing I can do at present to resolve this at the current point in time, but I will investigate.

**Comment by jadenthebebeng** [comment]
im having the same issueee

**Comment by lewisakura** [comment]
Resolved in https://github.com/lewisakura/RFU/releases/tag/5.5.0
