### ISSUE TITLE
RFU Corrupting my Roblox installation and causing crashes on startup

### ISSUE THREAD

**Issue by ShadeZinc46** [lewisakura/RFU#28]
**Describe the bug**
I was just hopping along, using RFU, then one day, Roblox updates, RFU console shows up telling me there was an error caused most likely by a new roblox update, and now even after I close RFU, delete the file, Roblox doesn't show up. Sometimes it has a crash, other times the process continues running in the background and has to be taskkilled. I have had so much frustration with this, uninstalling Roblox, and deleting every roblox file I could find. Nothing worked. I tried contacting Roblox support (they were useless, I had to wait a full day at at time only for them to tell me to do something I had already done). I finally fixed it by completely reinstalling Windows. That's now I isolated the problem. As soon as I loaded up RFU, it did the same thing. I'm not reinstalling Windows again because it screwed up my GPU, causing even more pain. I just don't understand why when I delete everything, it still is corrupted.

**To Reproduce**
1. Install RFU
2. Launch Roblox.
3. See error

**Expected behavior**
I expected Roblox to launch.

**Screenshots**
Nothing to screenshot. No errors, nothing.

**Desktop (please complete the following information):**
 - Version 5.4.5

**Comment by lewisakura** [comment]
If RFU isn't running, then it can't do anything to your game. RFU also does not modify files, only the client's memory. There is something else going on here that isn't related to me.

Also, if it's erroring, it isn't doing anything at all to your Roblox client. It's backing out of it because it can't edit the memory.

**Comment by ShadeZinc46** [comment]
Ah, I see. Any idea how I might fix it? 

Thanks for the quick response btw :3

**Comment by lewisakura** [comment]
Best I can think of is to uninstall it from Control Panel/Settings/whatever it is now on Windows and then reinstall from the website again.

**Comment by ShadeZinc46** [comment]
I already did that but thanks anyway.

**Comment by lewisakura** [comment]
You could also try blitzing the files from `%localappdata%/Roblox` to do a clean reinstall, in case it leaves anything behind. Beyond that, I'm not sure.
