### ISSUE TITLE
when ever i run the RFU and load into a game it doesnt work and keeps me at 30 fps

### ISSUE THREAD

**Issue by robloxisbroke** [lewisakura/RFU#7]
is anyone else getting a problem with the RFU not running and wont give u good fps when in a game cause i runned the fps unlocker then got into a game and caped me at 30 fps ive redownloaded it like 3 times and nothing works, ive tried everything and still it doesnt work

**Comment by robloxisbroke** [comment]
I cant get the RFU running cause whenever i do run it, it wont start it keeps me at 30 fps

**Comment by LewisTehMinerz** [comment]
Keeps you at 30? From 60? Sounds like it's doing its job then, but you've set the cap to 30FPS.

**Comment by robloxisbroke** [comment]
> Keeps you at 30? From 60? Sounds like it's doing its job then, but you've set the cap to 30FPS.

its not cap to 30 it was at none so it could run any fps

**Comment by LewisTehMinerz** [comment]
🤔 Can you send screenshots of the logs?

**Comment by robloxisbroke** [comment]
> 🤔 Can you send screenshots of the logs?

wdym logs?

**Comment by gabby1782** [comment]
same xdxd

**Comment by lewisakura** [comment]
No followup and CNR, also very old version.
